export const SET_LOADING_COURSES = 'SET_LOADING_COURSES';
export const SET_LOADING_AUTHORS = 'SET_LOADING_AUTHORS';
export const SET_LOADING_USER = 'SET_LOADING_USER';
export const SET_ERRORS = 'SET_ERRORS';
