export const SET_AUTHORS = 'SET_AUTHORS';
export const ADD_AUTHOR = 'ADD_AUTHORS';
export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_ERROR = 'FETCH_AUTHORS_ERROR';
